-- Revenue Intelligence: Add auto-draft tracking columns to ri_reply_drafts
-- needs_review: flags drafts that require human review before sending
-- source: origin of the draft ('ri' = auto-generated by RI pipeline)
-- Non-destructive — existing rows get defaults (needs_review=false, source=NULL).

ALTER TABLE public.ri_reply_drafts
  ADD COLUMN IF NOT EXISTS needs_review BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source TEXT;

-- Force PostgREST to pick up the new columns immediately.
NOTIFY pgrst, 'reload schema';
