import { Metadata } from 'next';
import Link from 'next/link';
import examples from '@/data/script-examples.json';
import { ExamplesGrid } from './ExamplesGrid';
import { PublicLayout } from '@/components/PublicLayout';

export const metadata: Metadata = {
  title: 'TikTok Script Examples — AI-Generated UGC Scripts | FlashFlow AI',
  description: 'Browse real AI-generated TikTok Shop scripts. See how FlashFlow creates unique scripts for every product and persona. Try free.',
  openGraph: {
    title: 'TikTok Script Examples — AI-Generated UGC Scripts',
    description: 'Browse real AI-generated TikTok Shop scripts. 12 examples across health, beauty, tech, home, and fashion.',
    type: 'website',
  },
};

const CATEGORIES = ['All', 'Health', 'Beauty', 'Home', 'Tech', 'Fashion'];

export default function ExamplesPage() {
  return (
    <PublicLayout>
      <div className="max-w-6xl mx-auto px-6 pb-20">
        {/* Hero */}
        <section className="text-center pt-12 pb-12">
          <h1 className="text-4xl sm:text-5xl font-bold leading-tight mb-4">
            Script Examples
          </h1>
          <p className="text-xl text-zinc-400 max-w-2xl mx-auto mb-8">
            Real scripts generated by FlashFlow AI. Different products, different personas,
            all ready to film.
          </p>
        </section>

        {/* Examples Grid with Client-Side Filtering */}
        <ExamplesGrid examples={examples} categories={CATEGORIES} />

        {/* CTA */}
        <section className="py-16 text-center">
          <div className="bg-zinc-900/60 border border-white/10 rounded-2xl p-8 sm:p-12">
            <h2 className="text-2xl font-bold mb-3">Generate scripts like these</h2>
            <p className="text-zinc-400 mb-6 max-w-lg mx-auto">
              Pick your product, choose a persona, and get a unique script in seconds.
              5 free scripts, no credit card required.
            </p>
            <Link href="/login?mode=signup" className="inline-block px-8 py-3.5 bg-teal-600 hover:bg-teal-500 text-white font-semibold rounded-xl transition-colors">
              Try FlashFlow Free
            </Link>
          </div>
        </section>
      </div>
    </PublicLayout>
  );
}
