import { Metadata } from 'next';
import Link from 'next/link';
import examples from '@/data/script-examples.json';
import { ExamplesGrid } from './ExamplesGrid';

export const metadata: Metadata = {
  title: 'TikTok Script Examples — AI-Generated UGC Scripts | FlashFlow AI',
  description: 'Browse real AI-generated TikTok Shop scripts. See how FlashFlow creates unique scripts for every product and persona. Try free.',
  openGraph: {
    title: 'TikTok Script Examples — AI-Generated UGC Scripts',
    description: 'Browse real AI-generated TikTok Shop scripts. 12 examples across health, beauty, tech, home, and fashion.',
    type: 'website',
  },
};

const CATEGORIES = ['All', 'Health', 'Beauty', 'Home', 'Tech', 'Fashion'];

export default function ExamplesPage() {
  return (
    <div className="min-h-screen bg-[#09090b] text-zinc-100">
      <div className="fixed inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:64px_64px] pointer-events-none" />

      {/* Header */}
      <header className="relative z-10 flex items-center justify-between max-w-6xl mx-auto px-6 py-6">
        <Link href="/" className="text-xl font-bold text-teal-400">FlashFlow AI</Link>
        <div className="flex items-center gap-4">
          <Link href="/login" className="text-sm text-zinc-400 hover:text-white transition-colors">Login</Link>
          <Link href="/login?mode=signup" className="text-sm px-4 py-2 bg-teal-600 hover:bg-teal-500 text-white rounded-lg transition-colors font-medium">
            Try Free
          </Link>
        </div>
      </header>

      <main className="relative z-10 max-w-6xl mx-auto px-6 pb-20">
        {/* Hero */}
        <section className="text-center pt-12 pb-12">
          <h1 className="text-4xl sm:text-5xl font-bold leading-tight mb-4">
            Script Examples
          </h1>
          <p className="text-xl text-zinc-400 max-w-2xl mx-auto mb-8">
            Real scripts generated by FlashFlow AI. Different products, different personas,
            all ready to film.
          </p>
        </section>

        {/* Examples Grid with Client-Side Filtering */}
        <ExamplesGrid examples={examples} categories={CATEGORIES} />

        {/* CTA */}
        <section className="py-16 text-center">
          <div className="bg-zinc-900/60 border border-white/10 rounded-2xl p-8 sm:p-12">
            <h2 className="text-2xl font-bold mb-3">Generate scripts like these</h2>
            <p className="text-zinc-400 mb-6 max-w-lg mx-auto">
              Pick your product, choose a persona, and get a unique script in seconds.
              5 free scripts, no credit card required.
            </p>
            <Link href="/login?mode=signup" className="inline-block px-8 py-3.5 bg-teal-600 hover:bg-teal-500 text-white font-semibold rounded-xl transition-colors">
              Try FlashFlow Free
            </Link>
          </div>
        </section>
      </main>

      <footer className="relative z-10 border-t border-white/5 py-8 text-center">
        <p className="text-xs text-zinc-600">
          &copy; 2026 FlashFlow AI by Making Miles Matter INC
        </p>
      </footer>
    </div>
  );
}
