import { Metadata } from 'next';
import Link from 'next/link';
import examples from '@/data/script-examples.json';
import { ExamplesGrid } from './ExamplesGrid';
import { PublicLayout } from '@/components/PublicLayout';

export const metadata: Metadata = {
  title: 'TikTok Script Examples — AI-Generated UGC Scripts | FlashFlow AI',
  description: 'Browse real AI-generated TikTok Shop scripts. See how FlashFlow creates unique scripts for every product and persona. Try free.',
  openGraph: {
    title: 'TikTok Script Examples — AI-Generated UGC Scripts',
    description: 'Browse real AI-generated TikTok Shop scripts. 12 examples across health, beauty, tech, home, and fashion.',
    type: 'website',
    images: [{ url: '/FFAI.png', width: 512, height: 512, alt: 'FlashFlow AI Logo' }],
    url: 'https://flashflowai.com/examples',
  },
  twitter: {
    card: 'summary',
    title: 'TikTok Script Examples | FlashFlow AI',
    description: 'Browse real AI-generated TikTok Shop scripts across health, beauty, tech, home, and fashion.',
    images: ['/FFAI.png'],
  },
  alternates: {
    canonical: 'https://flashflowai.com/examples',
  },
};

const CATEGORIES = ['All', 'Health', 'Beauty', 'Home', 'Tech', 'Fashion'];

export default function ExamplesPage() {
  return (
    <PublicLayout>
      <div className="max-w-6xl mx-auto px-6 pb-20">
        {/* Hero */}
        <section className="text-center pt-12 pb-12">
          <h1 className="text-4xl sm:text-5xl font-bold leading-tight mb-4">
            Script Examples
          </h1>
          <p className="text-xl text-zinc-400 max-w-2xl mx-auto mb-8">
            Real scripts generated by FlashFlow AI. Different products, different personas,
            all ready to film.
          </p>
        </section>

        {/* Examples Grid with Client-Side Filtering */}
        <ExamplesGrid examples={examples} categories={CATEGORIES} />

        {/* CTA */}
        <section className="py-16 text-center">
          <div className="bg-zinc-900/60 border border-white/10 rounded-2xl p-8 sm:p-12">
            <h2 className="text-2xl font-bold mb-3">Generate scripts like these — free</h2>
            <p className="text-zinc-400 mb-6 max-w-lg mx-auto">
              Pick your product, choose a persona, and get a unique script in seconds.
              No signup required to try.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/script-generator" className="px-8 py-3.5 bg-teal-600 hover:bg-teal-500 text-white font-semibold rounded-xl transition-colors">
                Try Free Script Generator
              </Link>
              <Link href="/transcribe" className="px-8 py-3.5 border border-teal-500/50 text-teal-400 font-semibold rounded-xl hover:bg-teal-500/10 transition-colors">
                TikTok Transcriber
              </Link>
              <Link href="/youtube-transcribe" className="px-8 py-3.5 border border-red-500/50 text-red-400 font-semibold rounded-xl hover:bg-red-500/10 transition-colors">
                YouTube Transcriber
              </Link>
            </div>
          </div>
        </section>
      </div>
    </PublicLayout>
  );
}
