/**
 * @module whop/plan-limits
 *
 * Per-plan monthly clip limits + enforcement / tracking helpers.
 * Reads from `ff_entitlements.plan` / `clips_generated` so the Whop
 * webhook stays the single writer of plan state.
 *
 * Keep this file small: one config table, one check, one increment.
 * Consumers (clip-generation code) import these two functions — they
 * should not reach into ff_entitlements directly.
 */

import { supabaseAdmin } from "@/lib/supabaseAdmin";

/** Sentinel for unlimited plans. Using Infinity lets `used < limit` work. */
export const UNLIMITED = Number.POSITIVE_INFINITY;

/**
 * Monthly clip limits keyed by ff_entitlements.plan.
 * 'lite' is an alias for 'starter' to keep pre-Whop users working.
 */
export const PLAN_CLIP_LIMITS: Record<string, number> = {
  free: 0,
  starter: 20,
  lite: 20,
  pro: 200,
  business: 200,
  brand: UNLIMITED,
  agency: UNLIMITED,
};

export const QUOTA_EXCEEDED_MESSAGE =
  "You've reached your monthly clip limit. Upgrade to continue.";

export interface QuotaCheck {
  allowed: boolean;
  plan: string;
  used: number;
  limit: number;
  /** Non-null when `allowed` is false — the user-facing reason. */
  message: string | null;
}

/**
 * Return whether the user can generate another clip. Does not mutate.
 * If the entitlement row is missing (e.g. brand-new signup hitting a
 * race), treat as free-tier = blocked rather than silently granting.
 */
export async function checkClipQuota(userId: string): Promise<QuotaCheck> {
  const { data, error } = await supabaseAdmin
    .from("ff_entitlements")
    .select("plan, status, clips_generated")
    .eq("user_id", userId)
    .maybeSingle();

  if (error) {
    console.error(`[whop/plan-limits] quota read failed for ${userId}:`, error);
    return { allowed: false, plan: "free", used: 0, limit: 0, message: QUOTA_EXCEEDED_MESSAGE };
  }

  const plan = data?.plan ?? "free";
  const used = data?.clips_generated ?? 0;
  const limit = PLAN_CLIP_LIMITS[plan] ?? 0;

  if (data?.status && data.status !== "active") {
    return { allowed: false, plan, used, limit, message: QUOTA_EXCEEDED_MESSAGE };
  }

  if (used >= limit) {
    return { allowed: false, plan, used, limit, message: QUOTA_EXCEEDED_MESSAGE };
  }

  return { allowed: true, plan, used, limit, message: null };
}

/**
 * Increment clips_generated by 1 atomically. Call exactly once per
 * successfully produced clip. Non-fatal on failure — logs and moves on.
 */
export async function incrementClipUsage(userId: string): Promise<void> {
  const { error } = await supabaseAdmin.rpc("ff_increment_clip_usage", { p_user_id: userId });
  if (error) {
    console.error(`[whop/plan-limits] increment failed for ${userId}:`, error);
  }
}

/** Same as above for source videos processed. Optional. */
export async function incrementVideoUsage(userId: string): Promise<void> {
  const { error } = await supabaseAdmin.rpc("ff_increment_video_usage", { p_user_id: userId });
  if (error) {
    console.error(`[whop/plan-limits] video increment failed for ${userId}:`, error);
  }
}
