'use client';

import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft } from 'lucide-react';
import { BRAND } from '@/lib/brand';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-300">
      {/* Header */}
      <header className="border-b border-white/10 bg-zinc-950/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <Image
              src={BRAND.logo}
              alt={BRAND.name}
              width={28}
              height={28}
              className="rounded-lg"
            />
            <span className="font-semibold text-zinc-100">{BRAND.name}</span>
          </Link>
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-zinc-400 hover:text-white transition-colors"
          >
            <ArrowLeft size={16} />
            Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
        <p className="text-zinc-500 mb-12">Last updated: February 1, 2026</p>

        <div className="prose prose-invert prose-zinc max-w-none space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using FlashFlow AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
            <p>
              FlashFlow AI is an AI-powered content generation platform that helps users create scripts,
              hooks, and video content ideas. The Service uses artificial intelligence to generate content
              based on user inputs and preferences.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">3. User Accounts</h2>
            <p className="mb-3">
              To access certain features, you must create an account. You agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorized use</li>
              <li>Accept responsibility for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">4. Content Ownership</h2>
            <p className="mb-3">
              <strong className="text-white">Your Content:</strong> You retain ownership of any content you input into the Service,
              including product information, brand details, and custom personas.
            </p>
            <p className="mb-3">
              <strong className="text-white">Generated Content:</strong> Content generated by our AI belongs to you. You may use,
              modify, and distribute generated scripts for any lawful purpose, including commercial use.
            </p>
            <p>
              <strong className="text-white">License to Us:</strong> You grant us a limited license to process your inputs
              for the purpose of generating content and improving our Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">5. Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate content that is illegal, harmful, or violates third-party rights</li>
              <li>Create misleading, deceptive, or fraudulent content</li>
              <li>Circumvent any content safety measures or filters</li>
              <li>Reverse engineer or attempt to extract our AI models</li>
              <li>Resell or redistribute the Service without authorization</li>
              <li>Use automated means to access the Service beyond normal usage</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">6. Payment Terms</h2>
            <p className="mb-3">
              <strong className="text-white">Subscription Plans:</strong> Paid features are available through monthly or annual
              subscription plans. Prices are listed on our pricing page and may change with notice.
            </p>
            <p className="mb-3">
              <strong className="text-white">Credits:</strong> AI generations consume credits according to your plan.
              Unused credits do not roll over to the next billing period.
            </p>
            <p className="mb-3">
              <strong className="text-white">Billing:</strong> Subscriptions automatically renew unless cancelled.
              You may cancel at any time through your account settings.
            </p>
            <p>
              <strong className="text-white">Refunds:</strong> We offer a 7-day money-back guarantee for new subscriptions.
              After 7 days, refunds are provided at our discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">7. AI-Generated Content Disclaimer</h2>
            <p className="mb-3">
              Content generated by our AI is created algorithmically and may not always be accurate, appropriate,
              or suitable for your specific use case. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Reviewing all generated content before use</li>
              <li>Ensuring content complies with applicable laws and platform policies</li>
              <li>Verifying factual claims made in generated content</li>
              <li>Editing content as needed for your brand and audience</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, FLASHFLOW AI SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
              WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
              INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">9. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. We will notify users of material changes via email
              or through the Service. Continued use after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">10. Termination</h2>
            <p>
              We may suspend or terminate your account for violations of these terms or for any reason
              with reasonable notice. Upon termination, you may export your data within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">11. Contact</h2>
            <p>
              For questions about these terms, please contact us at{' '}
              <a href="mailto:legal@flashflow.ai" className="text-blue-400 hover:underline">
                legal@flashflow.ai
              </a>
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/10 py-8 px-6">
        <div className="max-w-4xl mx-auto flex items-center justify-between text-sm text-zinc-500">
          <span>&copy; {new Date().getFullYear()} {BRAND.name}</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-zinc-300 transition-colors">Privacy Policy</Link>
            <Link href="/" className="hover:text-zinc-300 transition-colors">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
